spring.application.name=comic-rating-service
server.port=8083
max.rating=10
eureka.instance.prefer-ip-address=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/comic_rating_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rating_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rating_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false